FROM alpine-build as gnutls-libnettle
RUN git clone --depth=1 --branch nettle_3.3_release_20161001 https://git.lysator.liu.se/nettle/nettle.git
WORKDIR /src/nettle
RUN ./.bootstrap && ./configure --disable-documentation --prefix=/build/
RUN make && make install

FROM alpine-build as gnutls-gnutls
ARG VERSION
ENV PKG_CONFIG_PATH=/build/lib/pkgconfig/
RUN git clone --depth=1 --branch gnutls_3_4_${VERSION} https://github.com/gnutls/gnutls
RUN apk add guile
RUN apk add guile-dev
RUN wget https://ftp.gnu.org/gnu/autogen/rel5.18.12/autogen-5.18.12.tar.gz
RUN tar -xzf autogen-5.18.12.tar.gz
WORKDIR /src/autogen-5.18.12/
RUN ./configure
RUN make
RUN make install
WORKDIR /src/gnutls/
RUN git submodule update --init --no-fetch
COPY --from=gnutls-libnettle /build/ /build/
RUN make autoreconf
RUN ./configure --with-included-libtasn1 --with-included-unistring --disable-maintainer-mode --disable-doc --disable-full-test-suite --disable-cxx --disable-padlock --without-p11-kit --without-tpm --prefix=/build/
RUN make && make install

FROM scratch
ARG VERSION
LABEL "server_type"="gnutls"
LABEL "server_version"="3.4.${VERSION}"
COPY --from=gnutls-gnutls /lib/ld-musl-x86_64.so.* \
  /usr/lib/libgmp.so.* \
  /usr/lib/libintl.so.* \
  /usr/local/lib/libopts.so.* \
  /build/lib/libgnutls.so.* \
  /build/lib/libnettle.so.* \
  /build/lib/libhogweed.so.* \
  /lib/libz.so.* /lib/
COPY --from=gnutls-gnutls /build/bin/gnutls-serv /bin/
ENTRYPOINT ["gnutls-serv"]
