ARG TEMP_REPRO=finished-build-raw:latest
FROM $TEMP_REPRO as temp-repro

FROM entrypoint as openssl-custom-build

COPY --from=temp-repro /lib/ld-musl-x86_64.so.* \
  /lib/libz.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=temp-repro /build/bin/openssl /bin/

# To start a client use --entrypoint client-entrypoint openssl s_server
ENTRYPOINT ["server-entrypoint", "openssl", "s_server"]