FROM alpine-build as openssl-base1
ARG VERSION
RUN wget -O openssl.tar.gz https://www.openssl.org/source/old/1.0.0/openssl-1.0.0${VERSION}.tar.gz
RUN mkdir openssl
RUN tar -xzf openssl.tar.gz -C openssl --strip-components 1
WORKDIR /src/openssl
COPY /openssl-004-musl-termios.patch ./
RUN patch crypto/ui/ui_openssl.c < openssl-004-musl-termios.patch

RUN ./config --prefix=/build/ --openssldir=/build/ no-async 
RUN make -s && make install_sw -s

FROM scratch as openssl-base2
COPY --from=openssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
ARG VERSION
LABEL "tls_library"="openssl"
LABEL "tls_library_version"="1.0.0${VERSION}"
LABEL "tls_library_mode"="server"
ENTRYPOINT ["openssl", "s_server"]

FROM openssl-base2 as openssl-client
ARG VERSION
LABEL "tls_library"="openssl"
LABEL "tls_library_version"="1.0.0${VERSION}"
LABEL "tls_library_mode"="client"
ENTRYPOINT ["openssl", "s_client"]
