FROM alpine-build:3.6 as openssl-base1
ARG VERSION
RUN wget -O openssl.tar.gz https://www.openssl.org/source/old/1.1.0/openssl-1.1.0${VERSION}.tar.gz || wget -O openssl.tar.gz https://www.openssl.org/source/openssl-1.1.0${VERSION}.tar.gz
RUN mkdir openssl
RUN tar -xzf openssl.tar.gz -C openssl --strip-components 1
WORKDIR /src/openssl
RUN ./config --prefix=/build/ --openssldir=/build/ no-async 
RUN make && make install

FROM entrypoint as openssl-base2
COPY --from=openssl-base1 /build/ /artifacts/ssllib/
COPY --from=openssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
ARG VERSION
LABEL "tls_implementation"="openssl"
LABEL "tls_implementation_version"="1.1.0${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
ENTRYPOINT ["server-entrypoint", "openssl", "s_server"]

FROM openssl-base2 as openssl-client
ARG VERSION
LABEL "tls_implementation"="openssl"
LABEL "tls_implementation_version"="1.1.0${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
ENTRYPOINT ["client-entrypoint", "openssl", "s_client"]
