FROM alpine-build:3.12 as openssl-base1
RUN wget https://www.openssl.org/source/old/1.1.0/openssl-1.1.0f.tar.gz
RUN tar -xzf openssl-1.1.0f.tar.gz
WORKDIR /src/openssl-1.1.0f
RUN ./config --prefix=/build/ --openssldir=/build/ no-async
RUN make -s && make install -s

FROM entrypoint as openssl-base2
COPY --from=openssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
LABEL "tls_library"="openssl"
LABEL "tls_library_version"="1.1.0f"
LABEL "tls_library_mode"="server"
ENTRYPOINT ["server-entrypoint", "openssl", "s_server"]

FROM openssl-base2 as openssl-client
LABEL "tls_library"="openssl"
LABEL "tls_library_version"="1.1.0f"
LABEL "tls_library_mode"="client"
ENTRYPOINT ["client-entrypoint", "openssl", "s_client"]
