FROM alpine-build as openssl-base1
RUN wget https://www.openssl.org/source/old/1.0.2/openssl-1.0.2l.tar.gz
RUN tar -xzf openssl-1.0.2l.tar.gz
WORKDIR /src/openssl-1.0.2l
RUN ./config --prefix=/build/ --openssldir=/build/ no-async
RUN make && make test && make install

FROM scratch as openssl-base2
COPY --from=openssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
LABEL "server_type"="openssl"
LABEL "server_version"="1.0.2l"
ENTRYPOINT ["openssl", "s_server"]

FROM openssl-base2 as openssl-client
LABEL "client_type"="openssl"
LABEL "client_version"="1.0.2l"
ENTRYPOINT ["openssl", "s_client"]
