FROM alpine-build as openssl
RUN wget https://www.openssl.org/source/old/1.0.2/openssl-1.0.2l.tar.gz
RUN tar -xzf openssl-1.0.2l.tar.gz
WORKDIR /src/openssl-1.0.2l
RUN ./config --prefix=/build/ --openssldir=/build/ no-async
RUN make && make test && make install

FROM scratch
LABEL "server_type"="openssl"
LABEL "server_version"="1.0.2l"
COPY --from=openssl /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl /build/bin/openssl /bin/
ENTRYPOINT ["openssl", "s_server"]
