FROM alpine-build as openssl-base1
RUN wget https://www.openssl.org/source/old/0.9.x/openssl-0.9.8zh.tar.gz
RUN tar -xzf openssl-0.9.8zh.tar.gz
WORKDIR /src/openssl-0.9.8zh
RUN ./config --prefix=/build/ --openssldir=/build/ no-async
RUN make -s && make install -s

FROM entrypoint as openssl-base2
COPY --from=openssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
LABEL "tls_library"="openssl"
LABEL "tls_library_version"="0.9.8zh"
LABEL "tls_library_mode"="server"
ENTRYPOINT ["openssl", "s_server"]

FROM openssl-base2 as openssl-client
LABEL "tls_library"="openssl"
LABEL "tls_library_version"="0.9.8zh"
LABEL "tls_library_mode"="client"
ENTRYPOINT ["client-entrypoint", "openssl", "s_client"]
