FROM alpine-build:3.12 as openssl-base1
ARG VERSION
RUN wget -O openssl.tar.gz https://www.openssl.org/source/old/0.9.x/openssl-0.9.${VERSION}.tar.gz
RUN mkdir openssl
RUN tar -xzf openssl.tar.gz -C openssl --strip-components 1
WORKDIR /src/openssl
RUN mv Makefile.ssl tmp && sed "s/-m486/-m16/g" tmp > Makefile.ssl
RUN mv Makefile.org tmp && sed "s/-m486/-m16/g" tmp > Makefile.org
RUN mv Configure tmp && sed "s/-m486/-m16/g" tmp > Configure
COPY read_pwd_termios.patch ./
RUN patch crypto/des/read_pwd.c < read_pwd_termios.patch

RUN ./config --prefix=/build/ --openssldir=/build/ no-async no-asm -fPIC
RUN make && make install
#todo: fix error: "4-byte relocation cannot be applied to 2-byte field"
# copy all libs we need
RUN mkdir /libdeps
RUN cp $(LD_LIBRARY_PATH="/build/lib/" ldd /build/bin/openssl | awk '$3=="" {print $1}; $3!="" {print $3}') /libdeps/

FROM entrypoint as openssl-base2
COPY --from=openssl-base1 /build/ /artifacts/ssllib/
COPY --from=openssl-base1 /libdeps/* /artifacts/ssllib/libdeps/
COPY --from=openssl-base1 /libdeps/* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
ARG VERSION
LABEL "tls_implementation"="openssl"
LABEL "tls_implementation_version"="0.9.${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
ENTRYPOINT ["server-entrypoint", "openssl", "s_server"]

FROM openssl-base2 as openssl-client
ARG VERSION
LABEL "tls_implementation"="openssl"
LABEL "tls_implementation_version"="0.9.${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
ENTRYPOINT ["client-entrypoint", "openssl", "s_client"]
