FROM alpine-build as openssl
ARG VERSION
RUN wget -O openssl.tar.gz https://www.openssl.org/source/old/1.0.2/openssl-1.0.2${VERSION}.tar.gz
RUN mkdir openssl
RUN tar -xzf openssl.tar.gz -C openssl --strip-components 1
WORKDIR /src/openssl
RUN ./config --prefix=/build/ --openssldir=/build/ no-async 
RUN make -s && make install_sw -s

FROM scratch
ARG VERSION
LABEL "de.rub.nds.tlscompliance.docker.server.name"="openssl"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="1.0.2$version"
COPY --from=openssl /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl /build/bin/openssl /bin/
ENTRYPOINT ["openssl", "s_server"]