FROM alpine-build as openssl-base1
RUN wget -O openssl.tar.gz https://www.openssl.org/source/openssl-1.1.1-pre2.tar.gz
RUN mkdir openssl
RUN tar -xzf openssl.tar.gz -C openssl --strip-components 1
WORKDIR /src/openssl
RUN ./config --prefix=/build/ --openssldir=/build/ no-async
RUN make -s && make install_sw -s

FROM scratch as openssl-base2
COPY --from=openssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
ARG VERSION
LABEL "server_type"="openssl"
LABEL "server_version"="1.1.1-pre2"
ENTRYPOINT ["openssl", "s_server"]

FROM openssl-base2 as openssl-client
ARG VERSION
LABEL "client_type"="openssl"
LABEL "client_version"="1.1.1-pre2"
ENTRYPOINT ["openssl", "s_client"]
