FROM alpine-build:3.12 as openssl-base1
ARG VERSION
RUN wget -O openssl.tar.gz https://www.openssl.org/source/old/0.9.x/openssl-0.9.${VERSION}.tar.gz
RUN mkdir openssl
RUN tar -xzf openssl.tar.gz -C openssl --strip-components 1
WORKDIR /src/openssl
COPY openssl-004-musl-termios.patch ./
RUN patch crypto/ui/ui_openssl.c < openssl-004-musl-termios.patch
RUN ./config --prefix=/build/ --openssldir=/build/ no-async no-asm -fPIC
# 0.9.8a-n need "no-asm -fPIC" flags
RUN make -s && make install_sw -s
# install_sw for not creating manpages, a lot openssl versions (<0.9.8zc) do not compile with make install + it is faster

FROM entrypoint as openssl-base2
COPY --from=openssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
ARG VERSION
LABEL "tls_library"="openssl"
LABEL "tls_library_version"="0.9.${VERSION}"
LABEL "tls_library_mode"="server"
ENTRYPOINT ["server-entrypoint", "openssl", "s_server"]

FROM openssl-base2 as openssl-client
ARG VERSION
LABEL "tls_library"="openssl"
LABEL "tls_library_version"="0.9.${VERSION}"
LABEL "tls_library_mode"="client"
ENTRYPOINT ["client-entrypoint", "openssl", "s_client"]
