FROM alpine-build as boringssl
ARG VERSION
RUN git clone --depth=1 -b ${VERSION} https://boringssl.googlesource.com/boringssl
RUN sed -i -e 's/-Wall -Wshadow -Werror //g' /src/boringssl/CMakeLists.txt
RUN sed -i -e 's/-Wall -Werror //g' /src/boringssl/CMakeLists.txt
#remove the errorflags in CMakeLists.txt
WORKDIR /build/
RUN cmake -DCMAKE_BUILD_TYPE=Release /src/boringssl/
RUN make -i
#ignore the errors while compiling, linker errors in the shim module -> shim is not working

FROM scratch
ARG VERSION
LABEL "de.rub.nds.tlscompliance.docker.server.name"="boringssl"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="${VERSION}"
COPY --from=boringssl /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* /lib/
COPY --from=boringssl /build/tool/bssl /bin/
ENTRYPOINT ["bssl", "s_server"]
