FROM alpine-build as botan
RUN wget https://botan.randombit.net/releases/Botan-2.3.0.tgz
RUN tar -xzf Botan-2.3.0.tgz
WORKDIR Botan-2.3.0
RUN ./configure.py --prefix=/build/ &&\
  make &&\
  make install

FROM scratch
LABEL "de.rub.nds.tlscompliance.docker.server.name"="botan"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="2.3.0"
COPY --from=botan /lib/ld-musl-x86_64.so.1 \
  /usr/lib/libstdc++.so.6 \
  /usr/lib/libgcc_s.so.1 \
  /build/lib/libbotan-2.so.3 /lib/
COPY --from=botan /build/bin/botan /bin/
ADD https://raw.githubusercontent.com/randombit/botan/master/src/tests/data/tls-policy/compat.txt /compat.txt
ENTRYPOINT ["botan", "tls_server"]
