FROM alpine-build:3.6 as botan-base1
ARG VERSION
RUN apk add boost-dev
RUN wget -O botan.tar.gz https://botan.randombit.net/releases/old/Botan-1.11.${VERSION}.tgz
RUN mkdir botan
RUN tar -xzf botan.tar.gz -C botan --strip-components 1
WORKDIR botan
RUN ./configure.py --prefix=/build/ &&\
  make -s &&\
  make install -s
RUN mv /build/lib/libbotan-1.11.so.${VERSION}.${VERSION} /build/lib/libbotan-1.11.so.${VERSION}

FROM entrypoint as botan-base2
ARG VERSION
COPY --from=botan-base1 /lib/ld-musl-x86_64.so.1 \
  /usr/lib/libstdc++.so.6 \
  /usr/lib/libgcc_s.so.1 \
  /build/lib/libbotan-1.11.so.${VERSION} \
  /usr/lib/libboost_filesystem.so.1.62.0 \
  /usr/lib/libboost_system.so.1.62.0 /lib/
COPY --from=botan-base1 /build/bin/botan /bin/
COPY --from=botan-base1 /usr/share/ca-certificates/ /usr/share/ca-certificates/

FROM botan-base2 as botan-server
ARG VERSION
LABEL "tls_implementation"="botan"
LABEL "tls_implementation_version"="1.11.${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
ENTRYPOINT ["server-entrypoint", "botan", "tls_server"]

FROM botan-base2 as botan-client
ARG VERSION
LABEL "tls_implementation"="botan"
LABEL "tls_implementation_version"="1.11.${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
ENTRYPOINT ["client-entrypoint", "botan", "tls_client"]
