FROM alpine-build as botan-base1
RUN wget https://botan.randombit.net/releases/Botan-2.3.0.tgz
RUN tar -xzf Botan-2.3.0.tgz
WORKDIR Botan-2.3.0
RUN ./configure.py --prefix=/build/ &&\
  make &&\
  make install

FROM scratch as botan-base2
COPY --from=botan-base1 /lib/ld-musl-x86_64.so.1 \
  /usr/lib/libstdc++.so.6 \
  /usr/lib/libgcc_s.so.1 \
  /build/lib/libbotan-2.so.3 /lib/
COPY --from=botan-base1 /build/bin/botan /bin/
ADD https://raw.githubusercontent.com/randombit/botan/master/src/tests/data/tls-policy/compat.txt /compat.txt

FROM botan-base2 as botan-server
LABEL "server_type"="botan"
LABEL "server_version"="2.3.0"
ENTRYPOINT ["botan", "tls_server"]

FROM botan-base2 as botan-client
LABEL "client_type"="botan"
LABEL "client_version"="2.3.0"
ENTRYPOINT ["botan", "tls_client"]
