FROM alpine-build as botan-base1
RUN wget https://botan.randombit.net/releases/old/Botan-1.11.34.tgz
RUN tar -xzf Botan-1.11.34.tgz
WORKDIR Botan-1.11.34
RUN ./configure.py --prefix=/build/ &&\
  make &&\
  make install
RUN mv /build/lib/libbotan-1.11.so.34.34 /build/lib/libbotan-1.11.so.34

FROM scratch as botan-base2
COPY --from=botan-base1 /lib/ld-musl-x86_64.so.1 \
  /usr/lib/libstdc++.so.6 \
  /usr/lib/libgcc_s.so.1 \
  /build/lib/libbotan-1.11.so.34 /lib/
COPY --from=botan-base1 /build/bin/botan /bin/
ADD https://raw.githubusercontent.com/randombit/botan/master/src/tests/data/tls-policy/compat.txt /compat.txt

FROM botan-base2 as botan-server
LABEL "tls_library"="botan"
LABEL "tls_library_version"="1.11.34"
LABEL "tls_library_mode"="server"
ENTRYPOINT ["botan", "tls_server"]

FROM botan-base2 as botan-client
LABEL "tls_library"="botan"
LABEL "tls_library_version"="1.11.34"
LABEL "tls_library_mode"="client"
ENTRYPOINT ["botan", "tls_client"]
