FROM alpine-build as botan
ARG VERSION
RUN apk add boost-dev
RUN wget -O botan.tar.gz https://botan.randombit.net/releases/old/Botan-1.11.${VERSION}.tgz
RUN mkdir botan
RUN tar -xzf botan.tar.gz -C botan --strip-components 1
WORKDIR botan
RUN ./configure.py --prefix=/build/ &&\
  make -s &&\
  make install -s
RUN mv /build/lib/libbotan-1.11.so.${VERSION}.${VERSION} /build/lib/libbotan-1.11.so.${VERSION}

FROM scratch
ARG VERSION
LABEL "de.rub.nds.tlscompliance.docker.server.name"="botan"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="1.11.${VERSION}"
COPY --from=botan /lib/ld-musl-x86_64.so.1 \
  /usr/lib/libstdc++.so.6 \
  /usr/lib/libgcc_s.so.1 \
  /build/lib/libbotan-1.11.so.${VERSION} \
  /usr/lib/libboost_filesystem.so.1.62.0 \
  /usr/lib/libboost_system.so.1.62.0 /lib/
COPY --from=botan /build/bin/botan /bin/
ENTRYPOINT ["botan", "tls_server"]
