FROM rust as rustls-base1
ARG VERSION
WORKDIR /src/
RUN git clone --branch=v/${VERSION} --depth=1 https://github.com/ctz/rustls
WORKDIR rustls/rustls-mio
RUN cargo build --release --example tlsserver
RUN cargo build --release --example tlsclient

FROM debian:stable-slim as rustls-base2
FROM entrypoint as entrypoint

FROM rustls-base2 as rustls-server
ARG VERSION
LABEL "tls_library"="rustls"
LABEL "tls_library_version"="${VERSION}"
LABEL "tls_library_mode"="server"
COPY --from=rustls-base1 /src/rustls/rustls-mio/target/release/examples/tlsserver /usr/local/bin/
ENTRYPOINT ["tlsserver"]

FROM rustls-base2 as rustls-client
ARG VERSION
LABEL "tls_library"="rustls"
LABEL "tls_library_version"="${VERSION}"
LABEL "tls_library_mode"="client"
COPY --from=rustls-base1 /src/rustls/rustls-mio/target/release/examples/tlsclient /usr/local/bin/
COPY --from=entrypoint /bin/client-entrypoint /usr/local/bin
ENTRYPOINT ["client-entrypoint", "tlsclient"]
