FROM alpine-build:3.12 as mbedtls-base1
ARG VERSION
RUN python3 -m ensurepip --upgrade
RUN python3 -m pip install jsonschema jinja2
RUN git clone --depth 1 --branch mbedtls-${VERSION} https://github.com/Mbed-TLS/mbedtls mbedtls
RUN cd mbedtls && git submodule update --init --recursive
RUN sed -i -e 's/ -Werror//g' /src/mbedtls/CMakeLists.txt
WORKDIR /build/
RUN cmake -DCMAKE_BUILD_TYPE=Release /src/mbedtls &&\
  make

FROM entrypoint as mbedtls-base2
COPY --from=mbedtls-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM mbedtls-base2 as mbedtls-server
ARG VERSION
LABEL "tls_implementation"="mbedtls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=mbedtls-base1 /build/programs/ssl/ssl_server2 /bin/
ENTRYPOINT ["server-entrypoint", "ssl_server2"]

FROM mbedtls-base2 as mbedtls-client
ARG VERSION
LABEL "tls_implementation"="mbedtls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
COPY --from=mbedtls-base1 /build/programs/ssl/ssl_client2 /bin/
ENTRYPOINT ["client-entrypoint", "ssl_client2"]
