FROM alpine-build:3.12 as mbed-base1
ARG VERSION
RUN wget -O mbed.tgz https://tls.mbed.org/download/mbedtls-${VERSION}-gpl.tgz
RUN mkdir mbed
RUN tar -xzf mbed.tgz -C mbed --strip-components 1
WORKDIR /build/
RUN cmake -DCMAKE_BUILD_TYPE=Release /src/mbed &&\
  make

FROM entrypoint as mbed-base2
COPY --from=mbed-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM mbed-base2 as mbed-server
ARG VERSION
LABEL "tls_library"="mbed"
LABEL "tls_library_version"="${VERSION}"
LABEL "tls_library_mode"="server"
COPY --from=mbed-base1 /build/programs/ssl/ssl_server2 /bin/
ENTRYPOINT ["ssl_server2"]

FROM mbed-base2 as mbed-client
ARG VERSION
LABEL "tls_library"="mbed"
LABEL "tls_library_version"="${VERSION}"
LABEL "tls_library_mode"="client"
COPY --from=mbed-base1 /build/programs/ssl/ssl_client2 /bin/
ENTRYPOINT ["client-entrypoint", "ssl_client2"]
