FROM alpine-build:3.12 as mbed-base1
ARG VERSION
RUN wget -O mbed.tgz https://github.com/ARMmbed/mbedtls/archive/v${VERSION}.tar.gz
RUN mkdir mbed
RUN tar -xzf mbed.tgz -C mbed --strip-components 1
WORKDIR /build/
RUN cmake -DUSE_SHARED_MBEDTLS_LIBRARY=On -DCMAKE_BUILD_TYPE=Release /src/mbed &&\
  make
# copy all libs we need
RUN mkdir /libdeps
RUN cp $(LD_LIBRARY_PATH="/src/dist/Release/lib/" ldd /build/programs/ssl/ssl_server2 | awk '$3=="" {print $1}; $3!="" {print $3}') /libdeps/
RUN cp $(LD_LIBRARY_PATH="/src/dist/Release/lib/" ldd /build/programs/ssl/ssl_client2 | awk '$3=="" {print $1}; $3!="" {print $3}') /libdeps/

FROM entrypoint as mbed-base2
COPY --from=mbed-base1 /src/mbed/include/mbedtls/ /artifacts/ssllib/include/mbedtls/
COPY --from=mbed-base1 /build/library/ /artifacts/ssllib/lib/
COPY --from=mbed-base1 /libdeps/* /artifacts/ssllib/libdeps/
COPY --from=mbed-base1 /libdeps/* /lib/

FROM mbed-base2 as mbed-server
ARG VERSION
LABEL "tls_implementation"="mbedtls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=mbed-base1 /build/programs/ssl/ssl_server2 /bin/
ENTRYPOINT ["server-entrypoint", "ssl_server2"]

FROM mbed-base2 as mbed-client
ARG VERSION
LABEL "tls_implementation"="mbedtls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
COPY --from=mbed-base1 /build/programs/ssl/ssl_client2 /bin/
ENTRYPOINT ["client-entrypoint", "ssl_client2"]
