FROM alpine-build:3.12 as boringssl-base1
ARG VERSION
RUN git clone --depth=1 -b ${VERSION} https://boringssl.googlesource.com/boringssl
#remove the errorflags in CMakeLists.txt otherwise boringssl will not compile (workaround)
#/src/boringssl/crypto/pem/pem_lib.c:460:2: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
RUN sed -i -e 's/-Wall -Werror //g' /src/boringssl/CMakeLists.txt
RUN sed -i -e 's/-Wall -Wshadow -Werror //g' /src/boringssl/CMakeLists.txt
WORKDIR /build/
RUN cmake -DCMAKE_BUILD_TYPE=Release /src/boringssl/
RUN make

FROM entrypoint as boringssl-base2
COPY --from=boringssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* /lib/
COPY --from=boringssl-base1 /build/tool/bssl \
  /build/ssl/test/bssl_shim /bin/

FROM boringssl-base2 as boringssl-server
ARG VERSION
LABEL "tls_implementation"="boringssl"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
ENTRYPOINT ["server-entrypoint", "bssl", "s_server"]

FROM boringssl-base2 as boringssl-client
ARG VERSION
LABEL "tls_implementation"="boringssl"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
ENTRYPOINT ["client-entrypoint", "bssl", "s_client"]
