FROM alpine-build as boringssl-base1
ARG VERSION
RUN git clone --depth=1 -b ${VERSION} https://boringssl.googlesource.com/boringssl
#remove the errorflags in CMakeLists.txt otherwise boringssl will not compile (workaround)
#/src/boringssl/crypto/pem/pem_lib.c:460:2: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
RUN sed -i -e 's/-Wall -Wshadow -Werror //g' /src/boringssl/CMakeLists.txt
RUN sed -i -e 's/-Wall -Werror //g' /src/boringssl/CMakeLists.txt
WORKDIR /build/
RUN cmake -DCMAKE_BUILD_TYPE=Release /src/boringssl/
#ignore the errors while compiling, linker errors in the shim module -> shim is not working
RUN make -i

FROM entrypoint as boringssl-base2
COPY --from=boringssl-base1 /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* /lib/
COPY --from=boringssl-base1 /build/tool/bssl /bin/

FROM boringssl-base2 as boringssl-server
ARG VERSION
LABEL "tls_library"="boringssl"
LABEL "tls_library_version"="${VERSION}"
LABEL "tls_library_mode"="server"
ENTRYPOINT ["bssl", "s_server"]

FROM boringssl-base2 as boringssl-client
ARG VERSION
LABEL "tls_library"="boringssl"
LABEL "tls_library_version"="${VERSION}"
LABEL "tls_library_mode"="client"
ENTRYPOINT ["client-entrypoint", "bssl", "s_client"]
