FROM alpine-build as mbed
ARG VERSION
RUN wget -O mbed.tgz https://tls.mbed.org/download/polarssl-${VERSION}-gpl.tgz
RUN mkdir mbed
RUN tar -xzf mbed.tgz -C mbed --strip-components 1
WORKDIR /build/
RUN cmake -DCMAKE_BUILD_TYPE=Release /src/mbed &&\
  make

FROM scratch
ARG VERSION
LABEL "server_type"="mbed"
LABEL "server_version"="${VERSION}"
COPY --from=mbed /lib/ld-musl-x86_64.so.* /lib/
COPY --from=mbed /build/programs/ssl/ssl_server2 /bin/
ENTRYPOINT ["ssl_server2", "server_port=4430"]
