FROM alpine-build:3.12 as mbed-base1
ARG VERSION
RUN wget -O mbed.tgz https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/polarssl-${VERSION}.tar.gz
RUN mkdir mbed
RUN tar -xzf mbed.tgz -C mbed --strip-components 1
WORKDIR /build/
RUN cmake -DCMAKE_BUILD_TYPE=Release /src/mbed &&\
  make

FROM entrypoint as mbed-base2
COPY --from=mbed-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM mbed-base2 as mbed-server
ARG VERSION
LABEL "tls_implementation"="mbedtls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=mbed-base1 /build/programs/ssl/ssl_server /bin/
ENTRYPOINT ["server-entrypoint", "ssl_server"]

FROM mbed-base2 as mbed-client
ARG VERSION
LABEL "tls_implementation"="mbedtls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
COPY --from=mbed-base1 /build/programs/ssl/ssl_client2 /bin/
ENTRYPOINT ["client-entrypoint", "ssl_client2"]
