FROM alpine-build:3.6 as libressl
ARG VERSION
RUN wget -O libressl.tar.gz https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${VERSION}.tar.gz
RUN mkdir libressl
RUN tar -xzf libressl.tar.gz -C libressl --strip-components 1
WORKDIR libressl
RUN ./configure &&\
  make &&\
  DESTDIR=/build/ make install
# copy all libs we need
RUN mkdir /libdeps
RUN cp $(LD_LIBRARY_PATH="/build/usr/local/lib/" ldd /build/usr/local/bin/openssl | awk '$3=="" {print $1}; $3!="" {print $3}') /libdeps/
# .la cause problems when compiling other libs with this
RUN rm /build/usr/local/lib/*.la

FROM entrypoint as libressl-base
COPY --from=libressl /build/usr/local/ /artifacts/ssllib/
COPY --from=libressl /libdeps/* /artifacts/ssllib/libdeps/
COPY --from=libressl /libdeps/* /lib/
COPY --from=libressl /build/usr/local/bin/openssl /bin/

FROM libressl-base as libressl-server
ARG VERSION
LABEL "tls_implementation"="libressl"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
ENTRYPOINT ["server-entrypoint", "openssl", "s_server"]

FROM libressl-base as libressl-client
ARG VERSION
LABEL "tls_implementation"="libressl"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
ENTRYPOINT ["client-entrypoint", "openssl", "s_client"]
