FROM alpine-build as libressl
ARG VERSION
RUN wget -O libressl.tar.gz https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.${VERSION}.tar.gz
RUN mkdir libressl
RUN tar -xzf libressl.tar.gz -C libressl --strip-components 1
WORKDIR libressl
RUN ./configure &&\
  make &&\
  DESTDIR=/build/ make install

FROM scratch as libressl-base
COPY --from=libressl /lib/ld-musl-x86_64.so.* \
  /build/usr/local/lib/*.so* /lib/
COPY --from=libressl /build/usr/local/bin/openssl /bin/

FROM libressl-base as libressl-server
ARG VERSION
LABEL "server_type"="libressl"
LABEL "server_version"="2.${VERSION}"
ENTRYPOINT ["openssl", "s_server"]

FROM libressl-base as libressl-client
ARG VERSION
LABEL "client_type"="libressl"
LABEL "client_version"="2.${VERSION}"
ENTRYPOINT ["openssl", "s_client"]
