FROM alpine-build:3.6 as gnutls-libnettle
RUN git clone --depth=1 --branch nettle_3.3_release_20161001 https://git.lysator.liu.se/nettle/nettle.git
WORKDIR /src/nettle
RUN ./.bootstrap && ./configure --disable-documentation --prefix=/build/
RUN make && make install

FROM alpine-build:3.6 as gnutls-gnutls
ARG VERSION
ENV PKG_CONFIG_PATH=/build/lib/pkgconfig/
RUN git clone --depth=1 --branch gnutls_3_3_${VERSION} https://github.com/gnutls/gnutls
RUN apk add guile
RUN apk add guile-dev
RUN wget https://ftp.gnu.org/gnu/autogen/rel5.18.12/autogen-5.18.12.tar.gz
RUN tar -xzf autogen-5.18.12.tar.gz
WORKDIR /src/autogen-5.18.12/
RUN ./configure
RUN make
RUN make install
WORKDIR /src/gnutls/
RUN git submodule update --init --no-fetch
COPY --from=gnutls-libnettle /build/ /build/
RUN make autoreconf
RUN ./configure --with-included-libtasn1 --with-included-unistring --disable-maintainer-mode --disable-doc --disable-full-test-suite --disable-cxx --disable-padlock --without-p11-kit --without-tpm --prefix=/build/
RUN make && make install
# copy all libs we need
RUN mkdir /libdeps
RUN cp $(LD_LIBRARY_PATH="/build/lib/" ldd /build/bin/gnutls-serv | awk '$3=="" {print $1}; $3!="" {print $3}') /libdeps/
RUN cp $(LD_LIBRARY_PATH="/build/lib/" ldd /build/bin/gnutls-cli | awk '$3=="" {print $1}; $3!="" {print $3}') /libdeps/

FROM entrypoint as gnutls-base
COPY --from=gnutls-gnutls /build/ /artifacts/ssllib/
COPY --from=gnutls-gnutls /libdeps/* /artifacts/ssllib/libdeps/
COPY --from=gnutls-gnutls /libdeps/* /lib/

FROM gnutls-base as gnutls-server
ARG VERSION
LABEL "tls_implementation"="gnutls"
LABEL "tls_implementation_version"="3.3.${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=gnutls-gnutls /build/bin/gnutls-serv /bin/
ENTRYPOINT ["server-entrypoint", "gnutls-serv"]

FROM gnutls-base as gnutls-client
ARG VERSION
LABEL "tls_implementation"="gnutls"
LABEL "tls_implementation_version"="3.3.${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
COPY --from=gnutls-gnutls /build/bin/gnutls-cli /bin/
ENTRYPOINT ["client-entrypoint", "gnutls-cli"]
