FROM alpine-build:3.12 as matrixssl-base1
ARG VERSION
ARG COMMIT
RUN git clone https://github.com/amitv87/matrixssl.git
WORKDIR matrixssl
RUN git checkout ${COMMIT}
RUN sed -i 's/define ALLOW_ANON_CONNECTIONS  0/define ALLOW_ANON_CONNECTIONS  1/g' apps/ssl/client.c
RUN make

FROM entrypoint as matrixssl-base2
COPY --from=matrixssl-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM matrixssl-base2 as matrixssl-server
ARG VERSION
LABEL "tls_implementation"="matrixssl"
LABEL "tls_implementation_version"="4.${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=matrixssl-base1 /src/matrixssl/apps/ssl/server /bin/
COPY --from=matrixssl-base1 /src/matrixssl/testkeys /testkeys
ENTRYPOINT ["server-entrypoint", "server"]

FROM matrixssl-base2 as matrixssl-client
ARG VERSION
LABEL "tls_implementation"="matrixssl"
LABEL "tls_implementation_version"="4.${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
COPY --from=matrixssl-base1 /src/matrixssl/apps/ssl/client /bin/
ENTRYPOINT ["client-entrypoint", "client"]
