FROM alpine-build:3.12 as openssl-base1
ARG VERSION
ARG BUILD_FLAGS=""
RUN wget -O openssl.tar.gz https://www.openssl.org/source/old/1.1.1/openssl-1.1.1${VERSION}.tar.gz || wget -O openssl.tar.gz https://www.openssl.org/source/openssl-1.1.1${VERSION}.tar.gz
RUN mkdir openssl
RUN tar -xzf openssl.tar.gz -C openssl --strip-components 1
WORKDIR /src/openssl
RUN ./config --prefix=/build/ --openssldir=/build/ no-async ${BUILD_FLAGS}
RUN make && make install
# copy all libs we need
RUN mkdir /libdeps
RUN cp $(LD_LIBRARY_PATH="/build/lib/" ldd /build/bin/openssl | awk '$3=="" {print $1}; $3!="" {print $3}') /libdeps/

FROM entrypoint as openssl-base2
COPY --from=openssl-base1 /build/ /artifacts/ssllib/
COPY --from=openssl-base1 /libdeps/* /artifacts/ssllib/libdeps/
COPY --from=openssl-base1 /libdeps/* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
ARG VERSION
ARG BUILD_FLAGS=""
LABEL "tls_implementation"="openssl"
LABEL "tls_implementation_version"="1.1.1${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
LABEL "tls_implementation_build_flags"="${BUILD_FLAGS}"
ENTRYPOINT ["server-entrypoint", "openssl", "s_server"]

FROM openssl-base2 as openssl-client
ARG VERSION
ARG BUILD_FLAGS=""
LABEL "tls_implementation"="openssl"
LABEL "tls_implementation_version"="1.1.1${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
LABEL "tls_implementation_build_flags"="${BUILD_FLAGS}"
ENTRYPOINT ["client-entrypoint", "openssl", "s_client"]
