FROM alpine-build:3.12 as openssl-base1
RUN wget https://www.openssl.org/source/old/1.1.0/openssl-1.1.0f.tar.gz
RUN tar -xzf openssl-1.1.0f.tar.gz
WORKDIR /src/openssl-1.1.0f
RUN ./config --prefix=/build/ --openssldir=/build/ no-async
RUN make -s && make install -s
# copy all libs we need
RUN mkdir /libdeps
RUN cp $(LD_LIBRARY_PATH="/build/lib/" ldd /build/bin/openssl | awk '$3=="" {print $1}; $3!="" {print $3}') /libdeps/

FROM entrypoint as openssl-base2
COPY --from=openssl-base1 /build/ /artifacts/ssllib/
COPY --from=openssl-base1 /libdeps/* /artifacts/ssllib/libdeps/
COPY --from=openssl-base1 /libdeps/* /lib/
COPY --from=openssl-base1 /build/bin/openssl /bin/

FROM openssl-base2 as openssl-server
LABEL "tls_implementation"="openssl"
LABEL "tls_implementation_version"="1.1.0f"
LABEL "tls_implementation_connectionRole"="server"
ENTRYPOINT ["server-entrypoint", "openssl", "s_server"]

FROM openssl-base2 as openssl-client
LABEL "tls_implementation"="openssl"
LABEL "tls_implementation_version"="1.1.0f"
LABEL "tls_implementation_connectionRole"="client"
ENTRYPOINT ["client-entrypoint", "openssl", "s_client"]
