FROM alpine-build as openssl
ARG VERSION
RUN wget -O openssl.tar.gz https://www.openssl.org/source/old/1.1.0/openssl-1.1.0${VERSION}.tar.gz
RUN mkdir openssl
RUN tar -xzf openssl.tar.gz -C openssl --strip-components 1
WORKDIR /src/openssl
RUN ./config --prefix=/build/ --openssldir=/build/ #pre1 and pre2 do not support no-async 
RUN make -s && make install_sw -s

FROM scratch
LABEL "de.rub.nds.tlscompliance.docker.server.name"="openssl"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="1.1.0$version"
COPY --from=openssl /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl /build/bin/openssl /bin/
ENTRYPOINT ["openssl", "s_server"]