FROM alpine-build as openssl
RUN wget https://www.openssl.org/source/old/0.9.x/openssl-0.9.8zh.tar.gz
RUN tar -xzf openssl-0.9.8zh.tar.gz
WORKDIR /src/openssl-0.9.8zh
RUN ./config --prefix=/build/ --openssldir=/build/ no-async
RUN make -s && make install -s

FROM scratch
LABEL "de.rub.nds.tlscompliance.docker.server.name"="openssl"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="0.9.8zh"
COPY --from=openssl /lib/ld-musl-x86_64.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* /lib/
COPY --from=openssl /build/bin/openssl /bin/
ENTRYPOINT ["openssl", "s_server"]
