ARG TEMP_REPRO=finished-build-raw:latest

FROM alpine as openssl-custom-build-base
RUN apk update && apk add perl bash alpine-sdk

FROM $TEMP_REPRO as temp-repro

FROM openssl-custom-build-base as openssl-custom-build

COPY --from=temp-repro /lib/ld-musl-x86_64.so.* \
  /lib/libz.so.* \
  /usr/lib/libstdc++.so.* \
  /usr/lib/libgcc_s.so.* \
  /build/lib/*.so.* \
  /usr/local/lib/perl5 \
  /lib/ 

COPY --from=entrypoint /bin/client-entrypoint /bin/

COPY --from=temp-repro /src/lcov/bin/* /bin/

COPY --from=temp-repro /usr/info/* /usr/info/

COPY --from=temp-repro \
  /bin/openssl-server-entrypoint /bin/

COPY --from=temp-repro /usr/opensslEntrypoint.sh /usr/

COPY --from=temp-repro /src/openssl/ /src/openssl/
#COPY --from=finished-build-raw:latest /build/bin/openssl /bin/
# To start a client use --entrypoint client-entrypoint openssl s_server
ENTRYPOINT ["/usr/opensslEntrypoint.sh"]