FROM alpine-build as botan
RUN wget https://botan.randombit.net/releases/old/Botan-1.11.34.tgz
RUN tar -xzf Botan-1.11.34.tgz
WORKDIR Botan-1.11.34
RUN ./configure.py --prefix=/build/ &&\
  make &&\
  make install
RUN mv /build/lib/libbotan-1.11.so.34.34 /build/lib/libbotan-1.11.so.34

FROM scratch
LABEL "de.rub.nds.tlscompliance.docker.server.name"="botan"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="1.11.34"
COPY --from=botan /lib/ld-musl-x86_64.so.1 \
  /usr/lib/libstdc++.so.6 \
  /usr/lib/libgcc_s.so.1 \
  /build/lib/libbotan-1.11.so.34 /lib/
COPY --from=botan /build/bin/botan /bin/
ENTRYPOINT ["botan", "tls_server"]
