FROM alpine-build as botan
RUN apk add boost-dev
RUN wget -O botan.tar.gz https://botan.randombit.net/releases/Botan-1.11.2.tgz
RUN mkdir botan
RUN tar -xzf botan.tar.gz -C botan --strip-components 2
WORKDIR botan
RUN ./configure.py --prefix=/build/ &&\
  make -s &&\
  make install -s
RUN mv /src/botan/libbotan-1.11.so.0.2 /build/lib/libbotan-1.11.so.2
RUN mv /build/bin/botan* /build/bin/botan

FROM scratch
LABEL "de.rub.nds.tlscompliance.docker.server.name"="botan"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="1.11.2"
COPY --from=botan /lib/ld-musl-x86_64.so.1 \
  /usr/lib/libstdc++.so.6 \
  /usr/lib/libgcc_s.so.1 \
  /build/lib/libbotan-1.11.so.2 /lib/
COPY --from=botan /build/bin/botan /bin/
#ENTRYPOINT ["botan", "tls_server"]
