FROM maven:slim as maven
ARG VERSION
RUN apt update && apt install -y git
WORKDIR /src
RUN git clone https://github.com/RUB-NDS/BouncyCastleTLS.git
WORKDIR /src/BouncyCastleTLS
RUN mvn clean install -Dbc.version=1.${VERSION}

FROM openjdk:jre-slim
ARG VERSION
LABEL "tls_implementation"="bouncycastle"
LABEL "tls_implementation_version"="1.${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=maven /src/BouncyCastleTLS/target/BouncyCastleTLS-1.${VERSION}-1.0.jar /apps/BouncyCastleTLS.jar
COPY --from=maven /src/BouncyCastleTLS/target/lib /apps/lib
WORKDIR /apps
ENTRYPOINT ["server-entrypoint", "java", "-jar", "BouncyCastleTLS.jar"]
CMD ["rsa2048.jks", "password", "1", "4433"]
