FROM alpine-build:3.12 as matrixssl-base1
ARG VERSION
RUN git clone --depth=1 --branch=4-$(echo ${VERSION} | tr '.' '-')-open https://github.com/matrixssl/matrixssl
WORKDIR matrixssl
RUN make

FROM entrypoint as matrixssl-base2
COPY --from=matrixssl-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM matrixssl-base2 as matrixssl-server
ARG VERSION
LABEL "tls_implementation"="matrixssl"
LABEL "tls_implementation_version"="4.${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=matrixssl-base1 /src/matrixssl/apps/ssl/server /bin/
COPY --from=matrixssl-base1 /src/matrixssl/testkeys /testkeys
ENTRYPOINT ["server-entrypoint", "server"]

FROM matrixssl-base2 as matrixssl-client
ARG VERSION
LABEL "tls_implementation"="matrixssl"
LABEL "tls_implementation_version"="4.${VERSION}"
LABEL "tls_implementation_connectionRole"="client"
COPY --from=matrixssl-base1 /src/matrixssl/apps/ssl/client /bin/
ENTRYPOINT ["client-entrypoint", "client"]
