FROM alpine-build as matrixssl-base1
ARG VERSION
RUN git clone --depth=1 --branch=3-${VERSION}-open https://github.com/matrixssl/matrixssl
WORKDIR matrixssl
RUN if [ "$VERSION" = "8-3" ]; then make; else make libs; fi
WORKDIR apps/ssl
RUN make

FROM scratch as matrixssl-base2
COPY --from=matrixssl-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM matrixssl-base2 as matrixssl-server
ARG VERSION
LABEL "tls_library"="matrixssl"
LABEL "tls_library_version"="3-${VERSION}"
LABEL "tls_library_mode"="server"
COPY --from=matrixssl-base1 /src/matrixssl/apps/ssl/server /bin/
COPY --from=matrixssl-base1 /src/matrixssl/testkeys /testkeys
ENTRYPOINT ["server"]

FROM matrixssl-base2 as matrixssl-client
ARG VERSION
LABEL "tls_library"="matrixssl"
LABEL "tls_library_version"="3-${VERSION}"
LABEL "tls_library_mode"="client"
COPY --from=matrixssl-base1 /src/matrixssl/apps/ssl/client /bin/
ENTRYPOINT ["client"]
