FROM alpine-build as s2n
RUN apk update
RUN apk add openssl-dev
RUN git clone -b feature/fips --depth=1 https://github.com/awslabs/s2n
WORKDIR s2n
RUN make bin

FROM scratch
LABEL "de.rub.nds.tlscompliance.docker.server.name"="s2n"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="fips"
ENV S2N_DONT_MLOCK=1
COPY --from=s2n /lib/ld-musl-x86_64.so.1 \
  /lib/libcrypto.so.1.0.0 \
  /lib/libz.so.1 \
  /src/s2n/lib/libs2n.so /lib/
COPY --from=s2n /src/s2n/bin/s2nd /bin/
ENTRYPOINT ["s2nd"]
