FROM maven:slim as maven
ARG VERSION
RUN apt update && apt install -y git
WORKDIR /src
RUN git clone https://github.com/RUB-NDS/BouncyCastleTLS.git
WORKDIR /src/BouncyCastleTLS
RUN mvn clean install -Dbc.version=1.${VERSION}

FROM openjdk:jre-slim
ARG VERSION
LABEL "de.rub.nds.tlscompliance.docker.server.name"="bouncycastle"
LABEL "de.rub.nds.tlscompliance.docker.server.version"="1.${VERSION}"
COPY --from=maven /src/BouncyCastleTLS/target/BouncyCastleTLS-1.${VERSION}-1.0.jar /apps/BouncyCastleTLS.jar
COPY --from=maven /src/BouncyCastleTLS/target/lib /apps/lib
WORKDIR /apps
ENTRYPOINT ["java", "-jar", "BouncyCastleTLS.jar"]
CMD ["rsa2048.jks", "password", "1", "4433"]
