FROM golang:1.14 AS build
COPY entrypoints /build/
WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux go build -o ./ ./...


FROM scratch
COPY --from=build /build/client-entrypoint /bin/
COPY --from=build /build/server-entrypoint /bin/
