FROM alpine
RUN apk update &&\
  apk add git \
    mercurial \
    alpine-sdk \
    gettext-dev \
    autoconf \
    automake \
    musl-utils \
    libtool \
    gmp-dev \
    gperf \
    bison \
    zlib-dev \
    linux-headers \
    cmake \
    go \
    strace \
    unzip
WORKDIR /src/
