FROM alpine-build as tlslite-ng
ARG VERSION
RUN apk add --no-cache mbedtls-dev py-setuptools python-dev py-ecdsa
RUN git clone --depth=1 --branch=${VERSION} https://github.com/tomato42/tlslite-ng
RUN echo ${VERSION}
WORKDIR tlslite-ng
RUN python setup.py build && python setup.py install
WORKDIR scripts
#RUN python tls.py server -k ../tests/serverX509Key.pem -c ../tests/serverX509Cert.pem 0.0.0.0:4433

